
name: "Build and Deploy - Self Hosted"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GITHUB_WORKING_DIRECTORY: ''             # If you have a root folder in the GitHub code set otherwise leave it blank
  IIS_WEBAPP_PATH: 'C:\inetpub\wwwroot\WeatherAPI'   # Web App Path from Virtual Machine         
  DOTNET_VERSION: '7.0.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup .NET Core 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.GITHUB_WORKING_DIRECTORY }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ env.GITHUB_WORKING_DIRECTORY }}
        run: dotnet build --configuration Release --no-restore 

      - name: Publish
        working-directory: ${{ env.GITHUB_WORKING_DIRECTORY }}
        run: dotnet publish --configuration Release --output 'dotnetcorewebapp'

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: '${{ env.GITHUB_WORKING_DIRECTORY }}/dotnetcorewebapp'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download new binaries over the top of the app
      uses: actions/download-artifact@v4
      with:
        name: application
        path: ${{ env.IIS_WEBAPP_PATH }}
