name: Deploy to IIS

on:
  push:
    branches:
      - main  # Adjust this to match your repository's default branch

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: your-artifact-name
          path: C:\Temp\WeatherService-Artifacts  # Adjust the path where artifacts will be downloaded

      - name: Copy artifacts to IIS directory
        shell: pwsh
        run: |
          $source = "C:\Temp\WeatherService-Artifacts\*"
          $destination = "C:\inetpub\wwwroot\WeatherAPI"  # Adjust the destination directory
          Copy-Item -Path $source -Destination $destination -Recurse -Force

      - name: Restart IIS
        shell: pwsh
        run: |
          Restart-Service -Name W3SVC -Force
