name: C_&_T_BS_Deployment(To IIS)

on:
  push:
    branches:
      - main
env:
    TIME_OUT: 60000
    DOTNET_VERSION: '7.0.x'
    PROJECT_SOLUTION: './WeatherService/WeatherService.sln'
    PROJECT_SOLUTION_OUTPUT_FOLDER: './WeatherService/bin/Release/net6.0/'

jobs:
  checkMsDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: MsDeploy location
        run: |
          echo "Check MS deploy completed."
              
  deploy:
    runs-on: windows-latest
    needs: checkMsDeploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Web Deploy
        run: |
          choco install webdeploy -y

      - name: Build Website
        run: |
          # Add your build commands here if needed
          # For example, if your website is .NET-based:
             dotnet publish ${{env.PROJECT_SOLUTION}} --configuration Release --output ${{env.PROJECT_SOLUTION_OUTPUT_FOLDER}} --verbosity n

      - name: Deploy to Local IIS
        env:
          SERVER: "192.168.1.103:8080" # Change to your server name or IP
          USERNAME: ${{ secrets.ftp_username }} # Change to your Windows username
          PASSWORD: ${{ secrets.ftp_password }} # Set this secret in your repository's settings
        
        run: |
          $MSDeployPath = "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          $DownloadPath = "C:\inetpub\wwwroot\WeatherAPI"
          $Username = "${{ secrets.ftp_username }}"
          $Pwd = "${{ secrets.ftp_password }}"
          
          & "$MSDeployPath" -verb:sync -source:contentPath="$DownloadPath" -dest:auto,ComputerName="https://192.168.1.103:8080/MSDeploy.axd?site=WeatherAPI",UserName=$Username,Password=$Pwd,AuthType="Basic"
