name: C_&_T_BS_Deployment(To IIS)
on:
  push:
    branches:
      - main
      
env:
    TIME_OUT: 60000
    DOTNET_VERSION: '7.0.x'
    PROJECT_SOLUTION: './WeatherService/WeatherService.sln'
    PROJECT_SOLUTION_OUTPUT_FOLDER: './Release/'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .Net (Prerequisites)
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{env.DOTNET_VERSION}}
      
      - name: Restore 
        run: dotnet restore ${{env.PROJECT_SOLUTION}}

      - name: Build solution
        run: dotnet build ${{env.PROJECT_SOLUTION}} --configuration Release --no-restore

      # - name: Publish Artifact
      #   run: dotnet publish ${{env.PROJECT_SOLUTION}} --configuration Release --no-build --output ./Release
  
      - name: Push files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          port: ${{ secrets.ftp_port }}
          timeout: ${{ env.TIME_OUT }}
          local-dir: ${{ env.PROJECT_SOLUTION_OUTPUT_FOLDER }}
