name: C_&_T_BS_Deployment(To IIS)
on:
  push:
    branches:
      - main
      
env:
    TIME_OUT: 60000
    DOTNET_VERSION: '7.0.x'
    PROJECT_SOLUTION: './WeatherService/WeatherService.sln'
    PROJECT_SOLUTION_OUTPUT_FOLDER: './WeatherService/bin/Release/net6.0/'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .Net (Prerequisites)
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{env.DOTNET_VERSION}}
      
      - name: Restore 
        run: dotnet restore ${{env.PROJECT_SOLUTION}}

      - name: Build solution
        run: dotnet build ${{env.PROJECT_SOLUTION}} --configuration Release --no-restore

      # - name: Publish Artifact
      #   run: dotnet publish ${{env.PROJECT_SOLUTION}} --configuration Release --no-build --output ${{env.PROJECT_SOLUTION_OUTPUT_FOLDER}}

      - name: List directory contents
        run: |
            echo ${{ env.PROJECT_SOLUTION_OUTPUT_FOLDER }}
            ls -al ${{ env.PROJECT_SOLUTION_OUTPUT_FOLDER }}
            echo '*** Completed ***'
  
      - name: Copy files to local computer
        run: |
            git clone https://github.com/Collen-Dev/WeatherServices.git
            cd WeatherServices
            $dll_directory = ""
            if [ -d "${{env.PROJECT_SOLUTION_OUTPUT_FOLDER}}" ]; then
                cp -r "${{env.PROJECT_SOLUTION_OUTPUT_FOLDER}}" "C:\inetpub\TEST_FTP"
                echo "DLLs copied successfully."
            else
                echo "Directory ${{env.PROJECT_SOLUTION_OUTPUT_FOLDER}} does not exist."
            fi

