name: C_&_T_BS_Deployment(To IIS)
on:
  push:
    branches:
      - main
      
env:
    TIME_OUT: 60000
    DOTNET_VERSION: '7.0.x'
    PROJECT_SOLUTION: './WeatherService/WeatherService.sln'
    PROJECT_SOLUTION_OUTPUT_FOLDER: './WeatherService/bin/Release/net6.0/'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .Net (Prerequisites)
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{env.DOTNET_VERSION}}
      
      - name: Restore 
        run: dotnet restore ${{env.PROJECT_SOLUTION}}

      - name: Build solution
        run: dotnet build ${{env.PROJECT_SOLUTION}} --configuration Release --no-restore

      # - name: Publish Artifact
      #   run: dotnet publish ${{env.PROJECT_SOLUTION}} --configuration Release --no-build --output ${{env.PROJECT_SOLUTION_OUTPUT_FOLDER}}

      - name: List directory contents
        run: |
            echo ${{ env.PROJECT_SOLUTION_OUTPUT_FOLDER }}
            ls -al ${{ env.PROJECT_SOLUTION_OUTPUT_FOLDER }}
            echo '*** Completed ***'

      - name: Start Ngrok (Port Forwarding)
        uses: w9jds/ngrok-action@v2
        with:
          authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}    # Make sure to set NGROK_AUTH_TOKEN in your repository secrets
          region: eu                                    # Adjust this according to your preferred Ngrok region
          port: 22                                      # Adjust this according to the port your application runs on
  
      - name: Push files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          port: ${{ secrets.ftp_port }}
          timeout: ${{ env.TIME_OUT }}
          local-dir: ${{ env.PROJECT_SOLUTION_OUTPUT_FOLDER }}                                  # Adjust as required
          server-dir: './'                                                                      # Adjust as required
