name: C_&_T_BS_Deployment (Local IIS)
on:
  push:
    branches:
      - main
      
env:
    IIS_WEBAPP_PACAKGE_PATH: 'C:\inetpub\wwwroot\WeatherAPI'
    DOTNET_VERSION: '7.0.x'
    PROJECT_SOLUTION: './WeatherService/WeatherService.sln'
    APP_NAME_ARTIFACTS: 'Weather Service - Artifacts'

jobs:
  Preparation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .Net (Prerequisites)
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{env.DOTNET_VERSION}}
      
      - name: Restore 
        run: dotnet restore ${{env.PROJECT_SOLUTION}}

      - name: Build Project Solution
        run: dotnet build ${{env.PROJECT_SOLUTION}} --configuration Release --no-restore

  Deployment:
    runs-on: windows-latest

    steps:      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{env.APP_NAME_ARTIFACTS}}
          path: C:\temp\WeatherService-Artifacts  # Adjust the path where artifacts will be downloaded

      - name: Copy artifacts to IIS directory
        run: |
          robocopy C:\temp\WeatherService-Artifacts C:\inetpub\wwwroot\WeatherAPI /E /Z

      - name: Restart IIS
        run: iisreset /restart
        