name: C_&_T_BS_Deployment(To IIS)
on:
  push:
    branches:
      - main
      
env:
    FTP_SERVER: 'ftp://192.168.1.102'
    DOTNET_VERSION: '7.0.x'
    PROJECT_SOLUTION: './WeatherService/WeatherService.sln'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .Net (Prerequisites)
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{env.DOTNET_VERSION}}
      
      - name: Restore 
        run: dotnet restore ${{env.PROJECT_SOLUTION}}

      - name: Build solution
        run: dotnet build ${{env.PROJECT_SOLUTION}} --configuration Release --no-restore

      - name: Publish Artifact
        run: dotnet publish ${{env.PROJECT_SOLUTION}} --configuration Release --no-build
  
      - name: Push files
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ${{ env.FTP_SERVER }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
