name: C_&_T_BS_Deployment(To IIS)

on:
  push:
    branches:
      - main
env:
    TIME_OUT: 60000
    DOTNET_VERSION: '7.0.x'
    PROJECT_SOLUTION: './WeatherService/WeatherService.sln'
    PROJECT_SOLUTION_OUTPUT_FOLDER: './WeatherService/bin/Release/net6.0/'

jobs:
  checkMsDeploy:
    runs-on: windows-latest
    steps:
      - name: MsDeploy location
        run: |
          echo "C:\ProgramData\chocolatey\"
          ls -al "C:\ProgramData\chocolatey\"
          echo '*** Completed ***'
              
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Web Deploy
        run: |
          choco install webdeploy -y

      - name: Build Website
        run: |
          # Add your build commands here if needed
          # For example, if your website is .NET-based:
             dotnet publish ${{env.PROJECT_SOLUTION}} --configuration Release --output ${{env.PROJECT_SOLUTION_OUTPUT_FOLDER}} --verbosity n

      - name: Deploy to Local IIS
        env:
          SERVER: "192.168.1.103:8080" # Change to your server name or IP
          USERNAME: ${{ secrets.ftp_username }} # Change to your Windows username
          PASSWORD: ${{ secrets.ftp_password }} # Set this secret in your repository's settings
        run: |
          msdeploy -verb:sync -source:contentPath="C:\inetpub\wwwroot\WeatherAPI" -dest:auto,ComputerName="https://%SERVER%/MSDeploy.axd?site=WeatherAPI",UserName="%USERNAME%",Password="%PASSWORD%",AuthType="Basic"
