name: C_&_T_BS_Deployment (Local IIS)
on:
  push:
    branches:
      - main
      
env:
    IIS_WEBAPP_PACAKGE_PATH: 'C:\inetpub\wwwroot\WeatherAPI'
    DOTNET_VERSION: '7.0.x'
    PROJECT_SOLUTION: './WeatherService/WeatherService.sln'
    APP_NAME_ARTIFACTS: 'Weather Service - Artifacts'
    APP_NAME_ARTIFACTS_PATH: ''

jobs:
  Preparation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .Net (Prerequisites)
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{env.DOTNET_VERSION}}
      
      - name: Restore 
        run: dotnet restore ${{env.PROJECT_SOLUTION}}

      - name: Build Project Solution
        run: dotnet build ${{env.PROJECT_SOLUTION}} --configuration Release --no-restore

      - name: Publish Artifact
        run: dotnet publish ${{env.PROJECT_SOLUTION}} --configuration Release --no-build --output "${{env.APP_NAME_ARTIFACTS_PATH}}"

  Deployment:
    needs: Preparation
    runs-on: windows-latest

    steps:      
      - name: Copy artifacts to IIS directory
        run: |
          robocopy ${{env.APP_NAME_ARTIFACTS_PATH}} ${{env.IIS_WEBAPP_PACAKGE_PATH}} /E /Z

      - name: Restart IIS
        run: iisreset /restart
        